/*
 * Copyright (c) 2021. Christopher Willett
 * All Rights Reserved
 */

package us.anvildevelopment.cxnet.edge;

import us.anvildevelopment.cxnet.network.nodemesh.Node;

import java.io.Serializable;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * This object is ONLY accessible on the client device itself due to encryption
 */
public class DataContainer implements Serializable {
    public String test = "test";
    /**
     * Stores nodes that have allowed direct connections
     */
    public Map<String, Node> LAN = new HashMap<>();

    /**
     * Local peer address mapping for LAN discovery
     * Map: peerID -> List of local IP:port addresses (in priority order)
     *
     * Populated by:
     * - LAN scanner finding peers on local network
     * - Recording source addresses when events are received
     * - CXHELLO/CXHELLO_RESPONSE events
     *
     * Multiple addresses stored per peer for fallback routing:
     * - Primary: Listening port from CXHELLO payload
     * - Fallback: Ephemeral socket ports from passive discovery
     *
     * Used for direct local communication to bypass firewalls and improve performance
     */
    public Map<String, List<String>> localPeerAddresses = new ConcurrentHashMap<>();

    /**
     * Tracks the last added RECEIVING socket address (non-priority) per peer
     * Map: peerID -> last receiving socket address
     * Used to prevent address bloat by removing old receiving socket addresses when new ones arrive
     * Only tracks addresses added via priority=false (from NodeMesh recording source sockets)
     * Does NOT track CXHELLO addresses or other priority addresses
     */
    private Map<String, String> lastReceivingSocketPerPeer = new ConcurrentHashMap<>();

    /**
     * Whitelist: Registered nodes per network (for whitelist mode)
     * Map: networkID -> Set of registered node UUIDs
     *
     * SECURITY: Stored locally, NOT in seed. Only NMI/authorized backends maintain this.
     */
    public Map<String, Set<String>> networkRegisteredNodes = new ConcurrentHashMap<>();

    /**
     * Blocklist: Blocked nodes per network
     * Map: networkID -> (nodeID -> block reason)
     *
     * SECURITY: Stored locally, NOT in seed.
     */
    public Map<String, Map<String, String>> networkBlockedNodes = new ConcurrentHashMap<>();

    /**
     * Registration tokens for whitelist networks
     * Map: secureToken -> nodeID
     *
     * SECURITY: One-time use tokens generated by NMI/authorized backends
     * Used to authorize REGISTER_NODE events
     */
    public Map<String, String> registrationTokens = new ConcurrentHashMap<>();

    /**
     * This list is for storing waiting addresses in CX Address format, these will get picked up by CXHELLO and PeerFinding process in normal environments
     * Objects are generally received by PeerFinding response processing
     */
    public List<String> waitingAddresses = new ArrayList<>();

    /// CODE

    /**
     * Check if a node is registered to a network (whitelist check)
     */
    public boolean isNodeRegistered(String networkID, String nodeID) {
        Set<String> registered = networkRegisteredNodes.get(networkID);
        return registered != null && registered.contains(nodeID);
    }

    /**
     * Check if a node is blocked from a network
     */
    public boolean isNodeBlocked(String networkID, String nodeID) {
        Map<String, String> blocked = networkBlockedNodes.get(networkID);
        return blocked != null && blocked.containsKey(nodeID);
    }

    /**
     * Register a node to a network using a token
     * @return true if registration successful, false if token invalid
     */
    public boolean registerNode(String networkID, String nodeID, String token) {
        // Verify token matches nodeID
        String authorizedNodeID = registrationTokens.remove(token); // One-time use
        if (authorizedNodeID == null || !authorizedNodeID.equals(nodeID)) {
            return false;
        }

        // Add to registered nodes
        networkRegisteredNodes.computeIfAbsent(networkID, k -> new HashSet<>()).add(nodeID);
        return true;
    }

    /**
     * Block a node from a network
     */
    public void blockNode(String networkID, String nodeID, String reason) {
        networkBlockedNodes.computeIfAbsent(networkID, k -> new ConcurrentHashMap<>()).put(nodeID, reason);
    }

    /**
     * Unblock a node from a network
     */
    public String unblockNode(String networkID, String nodeID) {
        Map<String, String> blocked = networkBlockedNodes.get(networkID);
        return blocked != null ? blocked.remove(nodeID) : null;
    }

    /**
     * Generate a secure registration token for a node
     * @return secure token string
     */
    public String generateRegistrationToken(String nodeID) {
        String token = UUID.randomUUID().toString() + "-" + UUID.randomUUID().toString();
        registrationTokens.put(token, nodeID);
        return token;
    }

    /**
     * Record a local peer address for LAN communication
     * @param peerID Peer UUID
     * @param address Local IP:port address (e.g., "192.168.1.100:49152")
     * @param priority If true, add as first address (from CXHELLO payload); if false, append (passive discovery)
     */
    public void recordLocalPeer(String peerID, String address, boolean priority) {
        if (peerID != null && address != null && !address.isEmpty()) {
            List<String> addresses = localPeerAddresses.computeIfAbsent(peerID, k -> new java.util.ArrayList<>());

            // Don't add duplicates
            if (!addresses.contains(address)) {
                if (priority) {
                    // Priority address (from CXHELLO) - prepend and keep all
                    addresses.add(0, address);
                } else {
                    // Non-priority receiving socket - remove old socket before adding new
                    // This prevents address bloat from accumulating 60+ socket addresses per peer
                    String lastReceivingSocket = lastReceivingSocketPerPeer.get(peerID);
                    if (lastReceivingSocket != null) {
                        // Remove the previous receiving socket address
                        addresses.remove(lastReceivingSocket);
                    }

                    // Add new receiving socket address
                    addresses.add(address);

                    // Track this as the new last receiving socket
                    lastReceivingSocketPerPeer.put(peerID, address);
                }
            }
        }
    }

    /**
     * Record a local peer address (non-priority fallback)
     */
    public void recordLocalPeer(String peerID, String address) {
        recordLocalPeer(peerID, address, false);
    }

    /**
     * Get local address for a peer if available (returns first/priority address)
     * @param peerID Peer UUID
     * @return Local IP:port address, or null if not found
     */
    public String getLocalPeerAddress(String peerID) {
        List<String> addresses = localPeerAddresses.get(peerID);
        return (addresses != null && !addresses.isEmpty()) ? addresses.get(0) : null;
    }

    /**
     * Get all addresses for a peer (in priority order)
     * @param peerID Peer UUID
     * @return List of addresses, or empty list if not found
     */
    public List<String> getLocalPeerAddresses(String peerID) {
        List<String> addresses = localPeerAddresses.get(peerID);
        return (addresses != null) ? new java.util.ArrayList<>(addresses) : new java.util.ArrayList<>();
    }

    /**
     * Remove a local peer address
     * @param peerID Peer UUID
     */
    public void removeLocalPeer(String peerID) {
        localPeerAddresses.remove(peerID);
    }

    /**
     * Deprioritize failed routes by moving them to the end of the address list
     * Called when a successful route is found after some routes failed
     * @param peerID Peer UUID
     * @param successfulAddress The address that succeeded
     * @param numFailedRoutes Number of routes that failed before this one
     */
    public void deprioritizeFailedRoute(String peerID, String successfulAddress, int numFailedRoutes) {
        if (peerID == null || numFailedRoutes <= 0) return;

        List<String> addresses = localPeerAddresses.get(peerID);
        if (addresses == null || addresses.size() <= 1) return;

        // Find the successful address index
        int successIndex = addresses.indexOf(successfulAddress);
        if (successIndex <= 0) return; // Already at top or not found

        // Move all failed routes (addresses before the successful one) to the end
        // This ensures next time we try the successful route first
        synchronized (addresses) {
            List<String> failedRoutes = new java.util.ArrayList<>();
            for (int i = 0; i < successIndex; i++) {
                failedRoutes.add(addresses.get(i));
            }

            // Remove failed routes from their current positions
            addresses.removeAll(failedRoutes);

            // Add failed routes to the end (lowest priority)
            addresses.addAll(failedRoutes);

            System.out.println("[Route Reprioritize] " + peerID.substring(0, 8) +
                ": Moved " + failedRoutes.size() + " failed routes to end, " +
                successfulAddress + " now prioritized");
        }
    }

    /**
     * Get count of discovered local peers
     * @return Number of peers discovered via LAN/P2P
     */
    public int getLocalPeerCount() {
        return localPeerAddresses.size();
    }

    /**
     * Get all local peer addresses (map of peerID -> address list)
     */
    public Map<String, List<String>> getAllLocalPeerAddresses() {
        return new HashMap<>(localPeerAddresses);
    }
}

