/*
 * Copyright (c) 2026. Christopher Willett
 * All Rights Reserved
 */

package us.anvildevelopment.cxnet.network.events;

/**
 * Payload for CHECK_NETWORK_NAME and CHECK_NETWORK_NAME_RESPONSE events.
 *
 * CHECK_NETWORK_NAME (requester to CXNET backends via toBackends()):
 *   - {@code networkName}  the name to check
 *   - {@code requestId}    UUID generated by the requester; echoed in the response
 *                          so the CompletableFuture in ConnectX.pendingNameChecks can be completed
 *
 * CHECK_NETWORK_NAME_RESPONSE (first backend to respond, back to requester):
 *   - {@code networkName}  echoed from request
 *   - {@code requestId}    echoed from request
 *   - {@code taken}        true if the name is already registered
 *   - {@code message}      human-readable status
 */
public class NetworkNameCheck {
    public String networkName;
    public String requestId;
    public boolean taken;
    public String message;

    public NetworkNameCheck() {}
}