/*
 * Copyright (c) 2021. Christopher Willett
 * All Rights Reserved
 */

package dev.droppinganvil.v3.edge;

import dev.droppinganvil.v3.network.nodemesh.Node;

import java.io.Serializable;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * This object is ONLY accessible on the client device itself due to encryption
 */
public class DataContainer implements Serializable {
    public String test = "test";
    /**
     * Stores nodes that have allowed direct connections
     */
    public Map<String, Node> LAN = new HashMap<>();

    /**
     * Whitelist: Registered nodes per network (for whitelist mode)
     * Map: networkID -> Set of registered node UUIDs
     *
     * SECURITY: Stored locally, NOT in seed. Only NMI/authorized backends maintain this.
     */
    public Map<String, Set<String>> networkRegisteredNodes = new ConcurrentHashMap<>();

    /**
     * Blocklist: Blocked nodes per network
     * Map: networkID -> (nodeID -> block reason)
     *
     * SECURITY: Stored locally, NOT in seed.
     */
    public Map<String, Map<String, String>> networkBlockedNodes = new ConcurrentHashMap<>();

    /**
     * Registration tokens for whitelist networks
     * Map: secureToken -> nodeID
     *
     * SECURITY: One-time use tokens generated by NMI/authorized backends
     * Used to authorize REGISTER_NODE events
     */
    public Map<String, String> registrationTokens = new ConcurrentHashMap<>();

    /**
     * Check if a node is registered to a network (whitelist check)
     */
    public boolean isNodeRegistered(String networkID, String nodeID) {
        Set<String> registered = networkRegisteredNodes.get(networkID);
        return registered != null && registered.contains(nodeID);
    }

    /**
     * Check if a node is blocked from a network
     */
    public boolean isNodeBlocked(String networkID, String nodeID) {
        Map<String, String> blocked = networkBlockedNodes.get(networkID);
        return blocked != null && blocked.containsKey(nodeID);
    }

    /**
     * Register a node to a network using a token
     * @return true if registration successful, false if token invalid
     */
    public boolean registerNode(String networkID, String nodeID, String token) {
        // Verify token matches nodeID
        String authorizedNodeID = registrationTokens.remove(token); // One-time use
        if (authorizedNodeID == null || !authorizedNodeID.equals(nodeID)) {
            return false;
        }

        // Add to registered nodes
        networkRegisteredNodes.computeIfAbsent(networkID, k -> new HashSet<>()).add(nodeID);
        return true;
    }

    /**
     * Block a node from a network
     */
    public void blockNode(String networkID, String nodeID, String reason) {
        networkBlockedNodes.computeIfAbsent(networkID, k -> new ConcurrentHashMap<>()).put(nodeID, reason);
    }

    /**
     * Unblock a node from a network
     */
    public String unblockNode(String networkID, String nodeID) {
        Map<String, String> blocked = networkBlockedNodes.get(networkID);
        return blocked != null ? blocked.remove(nodeID) : null;
    }

    /**
     * Generate a secure registration token for a node
     * @return secure token string
     */
    public String generateRegistrationToken(String nodeID) {
        String token = UUID.randomUUID().toString() + "-" + UUID.randomUUID().toString();
        registrationTokens.put(token, nodeID);
        return token;
    }
}
